name: example_with_automated_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.2 <3.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  go_router: ^2.0.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.2
  cloud_functions: ^3.0.4
  email_validator: ^2.0.1
  equatable: ^2.0.3
  recase:


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_gherkin_integration: ^0.0.1-rc.1
  flutter_gherkin_automated:
    path: ../
  test: ^1.19.0
  test_api: 0.4.8
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  http: ^0.13.3
  fake_cloud_firestore: ^1.1.3

flutter:

  uses-material-design: true