name: flutter_gherkin_automated
description: A Gherkin / Cucumber automated bindings generator for Dart and Flutter
version: 0.0.1
homepage: https://github.com/PROGrand/flutter_gherkin_automated

environment:
  sdk: '>=2.14.3 <3.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ">=1.7.1 <3.0.0"
  build: ^2.1.1
  collection: ^1.15.0
  gherkin: ^2.0.5+1
  flutter_gherkin: ^3.0.0-rc.5
  glob: ^2.0.2
  source_gen: ^1.1.1


dev_dependencies:
  build_config: ^1.0.0
  lints: ^1.0.1
  meta: ^1.7.0
  build_runner: ^2.1.4


flutter:
