name: flutter_gherkin_automated
description: A Gherkin / Cucumber automated bindings generator for Dart and Flutter
version: 0.1.0-rc.2
homepage: https://github.com/PROGrand/flutter_gherkin_automated

environment:
  sdk: '>=2.14.2 <3.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  collection: ^1.15.0
  gherkin: ^2.0.8
  flutter_gherkin_integration: ^0.0.1-rc.1
  source_gen: ^1.1.1
  build: ^2.1.1
  glob: ^2.0.2
  clock: ^1.1.0

dev_dependencies:
  meta: ^1.7.0 
  pedantic: ^1.11.1
  build_config: ^1.0.0
  lints: ^1.0.1
  build_runner: ^2.1.4


flutter:
