workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    instance_type: mac_pro
    environment:
      vars:
        FIRESTORE_EMULATOR_HOST: localhost:8080
      node: 14.17.2
      npm: 6.14.13
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: false
    scripts:
      - name: Prepare Firebase tools and emulators
        script: |
          rm /usr/local/bin/firebase
          npm install -g firebase-tools
          cd functions
          npm install
      - name: Cloud function unit tests
        script: |
          unset GOOGLE_APPLICATION_CREDENTIALS
          set -e
          cd functions && firebase emulators:exec --project flutter-gherkin-automated --config ../local.firebase.json --only firestore,functions,auth "npm run ci-test"
          export GOOGLE_APPLICATION_CREDENTIALS=/Users/builder/builder-publisher.json
    publishing:
      slack:
        channel: '#codemagic-builds'
        notify_on_build_start: false